### PR TITLE
fix: Allow `#` and `@` in api param names

### PR DESCRIPTION
**Pull request by GentileFulvio**
I'll be honest not sure if you want this to be fixes but I had this issue mentioned here https://github.com/apidoc/apidoc/issues/899 that I can't use `#`'s in my param names. So I guess this fixes that.

There is still a failing test also mentioned in the issue linked. Didn't want to touch it though because it's not really part of this commit/issue as this commit fixes a specific issue (The test was already broken before I added any changes). I added a new test files that explicitly tests the `api_param` parser instead which seemed easier than the other tests you already have in the project. Let me know what you think.

Perhaps I should include other characters as well as mentioned in the following issues. https://github.com/apidoc/apidoc-core/issues/3 https://github.com/apidoc/apidoc-core/issues/64 https://github.com/apidoc/apidoc-core/issues/66

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Thanks!

I think it would be nice to include other characters too.

**Comment by GentileFulvio** [comment]
Could you provide a list of characters that should be accepted ?

`['#','@', ...]` ?

**Comment by NicolasCARPi** [comment]
The `.` too I believe.

**Comment by GentileFulvio** [comment]
Added the `@` added a test for the `.` as well apparently that should already work.

**Comment by NicolasCARPi** [comment]
Yes in fact the `.` is already used for array-like params.

**Comment by NicolasCARPi** [comment]
Thanks for your contribution!

**Pull request merged**
