### PR TITLE
Override allowed and default values from apidoc conf

### PR DESCRIPTION
**Pull request by guillaumeleone**
Hi,

We would like to override the 'allowed and default values' in parameter section (@apiParam) with values set in the apidoc.json file.

```
{
  ...
  "parameters": {
    "my_parameter": {
      "allowedValues" : ["my_allowed_value1", "my_allowed_value2"]
    },
    "my_other_parameter": {
      "defaultValue" : "my_default_value"
    }
  }
}
```

We propose this solution but we are not sure about it.

### CODE REVIEW

**Comment by guillaumeleone** [comment]
ping @rottmann 
The Api doc is still maintained ?

**Comment by rottmann** [comment]
Yes it is, but the last months i did not have enough time for it. Currently i am on holiday and my wife want to see me there too ;-)

**Comment by guillaumeleone** [comment]
Great! :-)

@rottmann When you have any time, we would like to discuss with you about this feature, because, for the moment, I have to fork apidoc-core for my company, and it's not clean.

**Comment by NicolasCARPi** [comment]
This is quite old now. Please open new PR if you want to merge some code ;)

**Pull request closed without merging**
