### PR TITLE
Security fix for ReDoS

### PR DESCRIPTION
**Pull request by ready-research**
Security fix for ReDoS vulnerability.
The adapted solution from: http://blog.stevenlevithan.com/archives/faster-trim-javascript
Reported in https://www.huntr.dev/bounties/3189c0b7-68fb-4372-a407-c6a19a22a3bf/

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your contribution.

An interesting read: https://overreacted.io/npm-audit-broken-by-design/

Static html is generated locally with known source by the dev. There is no risk for redos here, so I don't see the point of adding more code and potential bugs when the existing code works as expected.

**Comment by ready-research** [comment]
@NicolasCARPi Yes, no one will take an internal functionality directly to use. But when a user uses the apidoc-core package there might be a possibility of using this vulnerable functionality also. Security is all about edge cases. So recommending to fix this issue.

***Updated the fix with fewer code changes and more efficient***

**Comment by NicolasCARPi** [comment]
Why don't we use `str.trim()` only?

**Comment by ready-research** [comment]
Compatibility polyfill for [String.prototype.trim](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/Trim)

Yeah.. We can use str.trim() also if you don't find this as necessary.

**Comment by NicolasCARPi** [comment]
I think it's better to rely on "upstream" trim and not bother with custom regex introducing problems, as trim is not something new and is widely supported (actually since node 0.10 !). So this whole file (`trim.js`) is pointless and should be removed, with all calls to this trim changed to use the normal trim. Note that this file was introduced 7 years ago, when it might have made sense to have it. Not anymore.

**Comment by NicolasCARPi** [comment]
I could merge this, but it doesn't really bring value to the code. Are you willing to go over the codebase and replace all calls to utils/trim with `.trim()`? There are not that many.

**Comment by ready-research** [comment]
Closing this in https://github.com/apidoc/apidoc-core/pull/119

**Pull request closed without merging**
