### PR TITLE
added support for @apiTags

### PR DESCRIPTION
**Pull request by neelbhanushali**
PR for issue [apidoc/apidoc#832](https://github.com/apidoc/apidoc/issues/832)

* Might have created a lot of changes due to file formatting on save. If that is a problem, kindly let me know how do you guys format your files (html and js) while coding. I'll use the same plugin and update the PR.
* One more PR will be raised on `apidoc/apidoc` repo for updating the template
* I don't know how to write test for the package. Need someone to write them.

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your contribution. Do you think it would be possible to make a clean commit with NO reformatting?

And later do another PR with ONLY reformatting. It would help with the review and keeping a clean history with meaningful commits.

**Comment by neelbhanushali** [comment]
@NicolasCARPi I shall try to update the PR with reformatting

**Comment by neelbhanushali** [comment]
@NicolasCARPi I've updated the PR for formatting. Kindly have a look.

**Comment by neelbhanushali** [comment]
@NicolasCARPi @rottmann @manishsaraan Did you find time to review this PR?

**Comment by NicolasCARPi** [comment]
Note: this PR is left open until @rottmann can decide if it should be included. See https://github.com/apidoc/apidoc/issues/832#issuecomment-634634142

**Comment by NicolasCARPi** [comment]
Hello, this project is now deprecated, and code has been moved into the main apidoc repository. At the moment we will not add new tags, at least until the codebase cleanup is finished and most bugs have been squashed.

**Pull request closed without merging**
