### PR TITLE
remove lib wrench-js, because wrench-js project is deprecated

### PR DESCRIPTION
**Pull request by marshalys**
wrench-js project is deprecated, see: https://github.com/ryanmcgrath/wrench-js

### CODE REVIEW

**Comment by marshalys** [comment]
update mocha to avoid some warnings.

**Comment by marshalys** [comment]
fix #38

**Comment by Natinux** [comment]
@rottmann Can you please approve this PR ?

**Comment by rottmann** [comment]
Thanks, will integrage fs-exra with walkSync, so we did not need a custom function.

**Pull request closed without merging**
