### PR TITLE
Perl: handle =head[1-4] and =item as well as =pod

### PR DESCRIPTION
**Pull request by dallaylaen**
In Perl modules, =item or =head* are commonly used for documenting methods/functions

I'm not sure how to do unit testing for this though, would be grateful if anyone shown me. I only tested locally, aka "works on my machine".

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your contribution!

Could you please provide example perl code with the different cases?

**Comment by dallaylaen** [comment]
For instance, 

```perl
sub previous {
 ...
};

=item foo

@apiDescription This function does some foo().

=cut

sub foo {
};
```

If you hold on a bit, I think I'll be able to actually write tests for this on my own.

**Comment by NicolasCARPi** [comment]
> If you hold on a bit, I think I'll be able to actually write tests for this on my own.

That would be great yes :)

**Comment by NicolasCARPi** [comment]
At this point this is just too old so I'm going to close it, feel free to resubmit.

**Pull request closed without merging**
