### PR TITLE
apiConsumes and apiProduces annotations added

### PR DESCRIPTION
**Pull request by ipeluffo**
I added two new annotations to set the types that an api endpoint consumes and produces.
I hope you'll find them useful.

Cheers

### CODE REVIEW

**Comment by JasonAllenCorns** [comment]
Perfect, @ipeluffo !  This looks quite similar to the task I was just about to undertake, for noting sibling endpoints whose output is shared.

I wonder if you have a related PR planned for https://github.com/apidoc/apidocjs.com on how one uses these new annotations?

**Comment by ipeluffo** [comment]
Hey @JasonAllenCorns , at that moment I didn't realised that there was a repo for the website. 
Unfortunately, currently I don't have any related PR planned for it. I'll try to update it as soon as I have some time.
In any case, this PR should be merge before the website update :)

**Comment by JasonAllenCorns** [comment]
@ipeluffo - I created a fork and duplicated your PR in my own fork.  While I have the apiDoc build completing successfully, I can't seem to get the 'consumes' or 'produces' calls to _do_ anything.

Is the intended use something like this?

```
/** 
* @apiConsumes Some Thing it Consumes
**/
```

Are there additional intended fields, like "group" or "type" to be expected?

I asked about the Docs site, before, because the syntax for use, here, is not obvious.  Perhaps even comments in the PR could help?

**Comment by NicolasCARPi** [comment]
Based on the latest comment from @JasonAllenCorns , this PR doesn't seem working/complete. Closing.

**Pull request closed without merging**
